name: Generate PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate PDF
        run: |
          sudo apt-get install -y pandoc texlive-xetex
          pandoc README.md -s -o WHITEPAPER.pdf --pdf-engine=xelatex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: WHITEPAPER
          path: WHITEPAPER.pdf
          
      - name: Commit and push
        run: |
          git config user.name Bot
          git config user.email ai@bot.ua
          git add WHITEPAPER.pdf
          git commit -m "Update WHITEPAPER.pdf"
          git push
