name: Generate PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate PDF
        run: |
          sudo apt-get install -y pandoc texlive-xetex
          pandoc README.md -s -o README.pdf --pdf-engine=xelatex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: README
          path: README.pdf
          
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.pdf
          git commit -m "Add generated PDF"
          git push
